version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: nest_demo
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amb
      MYSQL_USER: amb
      MYSQL_PASSWORD: todo123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: